module.exports={
    PRODUCT_COLLECTIONS:'products',
    ADMIN_COLLECTIONS:'admin',
    VENDOR_COLLECTIONS:'vendors',
    CATEGORY_COLLECTIONS:'category',
    USER_COLLECTIONS:'user',
    CART_COLLECTIONS:"carts",
    ORDER_COLLECTIONS:"ORDERS"
}